import { Platform, StyleSheet } from 'react-native';
import { Colors } from '../../constants/colors';
import { Spacing } from '../../constants/spacing';

const AUTH_BLUE = '#2E6F8E';
const AUTH_TEXT = '#123A56';
const AUTH_MUTED = '#5F7F94';
const AUTH_SOFT = '#F7FAFC';
const AUTH_BORDER = '#E0E8ED';
const WEB_INPUT_RESET = Platform.OS === 'web'
  ? ({ outlineStyle: 'none', outlineWidth: 0, boxShadow: 'none' } as any)
  : {};

export const displayNameStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.foam,
    justifyContent: 'center',
    paddingHorizontal: 26,
    overflow: 'hidden',
  },
  wave1: {
    display: 'none',
  },
  wave2: {
    display: 'none',
  },
  dots: {
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'center',
    marginBottom: 34,
  },
  dot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: 'rgba(46,111,142,0.22)',
  },
  dotActive: {
    width: 20,
    backgroundColor: AUTH_BLUE,
  },
  content: { width: '100%' },
  stepWrap: { alignItems: 'center' },
  bigEmoji: {
    fontSize: 1,
    height: 0,
    marginBottom: 0,
  },
  title: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 23,
    lineHeight: 29,
    color: AUTH_TEXT,
    textAlign: 'center',
    marginBottom: 8,
  },
  subtitle: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 14,
    color: AUTH_MUTED,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 8,
  },
  hint: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 12,
    color: '#91A8B7',
    textAlign: 'center',
    marginBottom: 18,
  },
  input: {
    ...WEB_INPUT_RESET,
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    borderWidth: 0.8,
    borderColor: AUTH_BORDER,
    paddingHorizontal: Spacing.md,
    paddingVertical: 14,
    fontSize: 16,
    fontFamily: 'Nunito_400Regular',
    color: AUTH_TEXT,
    width: '100%',
    textAlign: 'center',
  },
  preview: {
    fontFamily: 'Nunito_600SemiBold',
    fontSize: 13,
    color: AUTH_BLUE,
    marginTop: 8,
  },
  actionSlot: {
    width: '100%',
    marginTop: 26,
  },
  ageControlSlot: {
    width: 180,
    height: 174,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 4,
  },
  ageTouchable: {
    width: 158,
    height: 154,
  },

  pickerWrap: {
    width: 158,
    height: 154,
    overflow: 'hidden',
    position: 'relative',
    borderRadius: 22,
    borderWidth: 0.8,
    borderColor: AUTH_BORDER,
    backgroundColor: AUTH_SOFT,
  },
  pickerList: {
    position: 'relative',
    zIndex: 2,
  },
  pickerOverlayTop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 54,
    zIndex: 3,
    backgroundColor: '#F9FBFC',
    opacity: 0.84,
  },
  pickerOverlayBottom: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 54,
    zIndex: 3,
    backgroundColor: '#F1F5F7',
    opacity: 0.84,
  },
  pickerSelector: {
    position: 'absolute',
    top: 54,
    left: 12,
    right: 12,
    height: 46,
    borderWidth: 0.8,
    borderColor: AUTH_BORDER,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    zIndex: 1,
    shadowColor: '#1A3A5C',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 1,
  },
  pickerItem: {
    height: 46,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pickerSpacer: {
    height: 54,
  },
  pickerItemText: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 19,
    color: '#A8BAC5',
  },
  pickerItemTextActive: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 23,
    color: AUTH_TEXT,
  },
  manualInput: {
    ...WEB_INPUT_RESET,
    width: 158,
    height: 54,
    backgroundColor: AUTH_SOFT,
    borderRadius: 18,
    borderWidth: 0.8,
    borderColor: AUTH_BORDER,
    paddingHorizontal: 18,
    fontSize: 22,
    fontFamily: 'Nunito_700Bold',
    color: AUTH_TEXT,
    textAlign: 'center',
    textAlignVertical: 'center',
  },

  error: {
    color: Colors.alertHigh,
    fontSize: 13,
    fontFamily: 'Nunito_400Regular',
    textAlign: 'center',
    marginTop: 4,
  },
  btnPrimary: {
    backgroundColor: AUTH_BLUE,
    borderRadius: Spacing.radiusFull,
    paddingVertical: 16,
    alignItems: 'center',
    width: '100%',
    marginTop: 26,
    shadowColor: AUTH_BLUE,
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 4,
  },
  btnDisabled: { opacity: 0.45 },
  btnText: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 16,
    color: Colors.textLight,
  },
  btnSkip: {
    marginTop: 12,
    padding: 6,
    alignSelf: 'center',
  },
  skipText: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 13,
    color: '#91A8B7',
    textDecorationLine: 'underline',
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(12, 44, 58, 0.55)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  modalCard: {
    width: '100%',
    maxWidth: 340,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    paddingVertical: 28,
    paddingHorizontal: 24,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 24,
    elevation: 8,
  },
  modalEmoji: {
    fontSize: 48,
    marginBottom: 8,
  },
  modalTitle: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 20,
    color: AUTH_TEXT,
    marginBottom: 6,
  },
  modalText: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 14,
    color: Colors.textSecondary,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 20,
  },
  modalActionSlot: {
    width: '100%',
  },
  modalBtn: {
    backgroundColor: AUTH_BLUE,
    borderRadius: Spacing.radiusFull,
    paddingVertical: 14,
    paddingHorizontal: 32,
    width: '100%',
    alignItems: 'center',
  },
  modalBtnText: {
    fontFamily: 'Nunito_600SemiBold',
    fontSize: 15,
    color: Colors.textLight,
  },
});
