import { StyleSheet } from 'react-native';

export const primaryCtaStyles = StyleSheet.create({
  wrap: {
    paddingHorizontal: 20,
    marginTop: 22,
  },
  btn: {
    backgroundColor: '#2E6F8E',
    borderRadius: 30,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#2E6F8E',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.30,
    shadowRadius: 16,
    elevation: 6,
  },
  btnText: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 15,
    color: '#FFFFFF',
  },
});

export const soraPromoStyles = StyleSheet.create({
  wrap: {
    marginTop: 24,
    marginHorizontal: 20,
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    shadowColor: '#1A3A4A',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.12,
    shadowRadius: 14,
    elevation: 4,
  },
  textBlock: {
    flex: 1,
  },
  title: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 16,
    color: '#1A3A4A',
    lineHeight: 21,
  },
  body: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 13,
    color: '#6E8597',
    lineHeight: 18,
    marginTop: 8,
    marginBottom: 12,
  },
  ctaPill: {
    alignSelf: 'flex-start',
    backgroundColor: '#2E6F8E',
    borderRadius: 22,
    paddingHorizontal: 18,
    paddingVertical: 8,
    shadowColor: '#2E6F8E',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 3,
  },
  ctaPillText: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 13,
    color: '#FFFFFF',
  },
  mascot: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#C4DDED',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#5B9BC8',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 4,
  },
  mascotGlyph: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 22,
    color: '#2E6F8E',
  },
});
