import { StyleSheet } from 'react-native';

const GREEN_DEEP = '#143A25';
const GREEN_MAIN = '#2F7248';
const GREEN_SOFT = '#DDECDD';

export const meditationSessionStyles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: GREEN_MAIN,
  },
  screen: {
    flex: 1,
    backgroundColor: GREEN_MAIN,
    paddingHorizontal: 24,
    paddingTop: 10,
    paddingBottom: 28,
  },
  header: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  iconButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.14)',
  },
  headerTitle: {
    flex: 1,
    fontFamily: 'Nunito_700Bold',
    fontSize: 16,
    color: '#FFFFFF',
    textAlign: 'center',
    marginHorizontal: 12,
  },
  placeholder: {
    width: 42,
    height: 42,
  },
  loadingWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
  },
  loadingText: {
    fontFamily: 'Nunito_600SemiBold',
    fontSize: 14,
    color: '#FFFFFF',
  },
  content: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  soundName: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 21,
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 8,
  },
  soundDesc: {
    maxWidth: 300,
    fontFamily: 'Nunito_400Regular',
    fontSize: 13,
    lineHeight: 19,
    color: 'rgba(255,255,255,0.78)',
    textAlign: 'center',
    marginBottom: 34,
  },
  clockWrap: {
    width: 268,
    height: 268,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 34,
  },
  waveRing: {
    position: 'absolute',
    width: 188,
    height: 188,
    borderRadius: 94,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.55)',
  },
  clockFace: {
    position: 'absolute',
    width: 196,
    height: 196,
    borderRadius: 98,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: GREEN_SOFT,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.7)',
    shadowColor: '#062014',
    shadowOpacity: 0.22,
    shadowOffset: { width: 0, height: 18 },
    shadowRadius: 28,
    elevation: 8,
  },
  progressSvg: {
    position: 'absolute',
  },
  countdown: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 42,
    color: GREEN_DEEP,
    textAlign: 'center',
    letterSpacing: 0,
  },
  timerCaption: {
    fontFamily: 'Nunito_600SemiBold',
    fontSize: 13,
    color: '#5F8669',
    marginTop: 4,
  },
  statusText: {
    fontFamily: 'Nunito_600SemiBold',
    fontSize: 15,
    color: 'rgba(255,255,255,0.86)',
    textAlign: 'center',
    minHeight: 24,
  },
  statusTextHidden: {
    opacity: 0,
  },
  saveText: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 12,
    color: 'rgba(255,255,255,0.68)',
    textAlign: 'center',
    marginTop: 6,
    minHeight: 18,
  },
  actions: {
    gap: 12,
  },
  primaryButton: {
    minHeight: 54,
    borderRadius: 28,
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 22,
    shadowColor: '#062014',
    shadowOpacity: 0.16,
    shadowOffset: { width: 0, height: 10 },
    shadowRadius: 18,
    elevation: 5,
  },
  primaryButtonText: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 15,
    color: GREEN_DEEP,
    textAlign: 'center',
  },
  secondaryButton: {
    minHeight: 50,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.45)',
    backgroundColor: 'rgba(255,255,255,0.08)',
    paddingHorizontal: 22,
  },
  secondaryButtonText: {
    fontFamily: 'Nunito_600SemiBold',
    fontSize: 14,
    color: '#FFFFFF',
    textAlign: 'center',
  },
  dangerButtonText: {
    color: '#FFE6E0',
  },
  errorCard: {
    width: '100%',
    maxWidth: 340,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderRadius: 24,
    paddingVertical: 26,
    paddingHorizontal: 20,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
  },
  errorTitle: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 18,
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 8,
  },
  errorBody: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 13,
    lineHeight: 19,
    color: 'rgba(255,255,255,0.78)',
    textAlign: 'center',
    marginBottom: 18,
  },
  dialogBackdrop: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    justifyContent: 'center',
    paddingHorizontal: 18,
    backgroundColor: 'rgba(20,58,37,0.24)',
  },
  dialogCard: {
    width: '100%',
    maxWidth: 342,
    alignSelf: 'center',
    borderRadius: 24,
    backgroundColor: '#F7FCF6',
    paddingVertical: 20,
    paddingHorizontal: 18,
    shadowColor: '#062014',
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 14 },
    shadowRadius: 24,
    elevation: 9,
  },
  dialogTitle: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 17,
    color: GREEN_DEEP,
    textAlign: 'center',
    marginBottom: 8,
  },
  dialogBody: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 13,
    lineHeight: 20,
    color: '#456B51',
    textAlign: 'center',
  },
  dialogActions: {
    gap: 10,
    marginTop: 18,
  },
  dialogPrimaryButton: {
    minHeight: 52,
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 18,
    shadowColor: '#062014',
    shadowOpacity: 0.12,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 16,
    elevation: 4,
  },
  dialogPrimaryButtonText: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 15,
    color: GREEN_DEEP,
    textAlign: 'center',
  },
  dialogSecondaryButton: {
    minHeight: 50,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#9FC6A9',
    backgroundColor: '#EAF5EA',
    paddingHorizontal: 18,
  },
  dialogSecondaryButtonText: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 14,
    color: GREEN_DEEP,
    textAlign: 'center',
  },
  dialogDangerButton: {
    minHeight: 50,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#F0B8AD',
    backgroundColor: '#FFF2EF',
    paddingHorizontal: 18,
  },
  dialogDangerButtonText: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 14,
    color: '#B54838',
    textAlign: 'center',
  },
  dialogButtonDisabled: {
    opacity: 0.48,
  },
  awayCard: {
    position: 'absolute',
    left: 24,
    right: 24,
    bottom: 28,
    borderRadius: 24,
    backgroundColor: '#F4FAF4',
    paddingVertical: 18,
    paddingHorizontal: 18,
    shadowColor: '#062014',
    shadowOpacity: 0.18,
    shadowOffset: { width: 0, height: 14 },
    shadowRadius: 24,
    elevation: 8,
  },
  awayTitle: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 16,
    color: GREEN_DEEP,
    textAlign: 'center',
    marginBottom: 6,
  },
  awayBody: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 13,
    lineHeight: 19,
    color: '#5F8669',
    textAlign: 'center',
    marginBottom: 14,
  },
});
