import { StyleSheet } from 'react-native';
import { Colors } from '../../constants/colors';

const TRACKER_ACTION_BLUE = '#2E6F8E';

export const trackerScreenStyles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 20,
  },
  headerTitle: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 28,
    color: Colors.textPrimary,
    marginBottom: 4,
  },
  headerSub: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 14,
    color: Colors.textSecondary,
  },
  completedBadge: {
    backgroundColor: Colors.teal,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 8,
    alignItems: 'center',
  },
  completedText: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 19,
    color: Colors.textLight,
  },
  completedLabel: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 10,
    color: 'rgba(255,255,255,0.8)',
  },
  streakBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF3E0',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 8,
    gap: 6,
    borderWidth: 1,
    borderColor: '#FFD59E',
  },
  streakBadgeCold: {
    backgroundColor: '#EEF4F8',
    borderColor: '#D6E4EE',
  },
  streakFlame: {
    fontSize: 18,
  },
  streakNum: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 18,
    color: '#E65100',
  },
  streakNumCold: {
    color: Colors.textSecondary,
  },
  streakLabel: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 11,
    color: '#8B5A2B',
  },
  streakLabelCold: {
    color: Colors.textSecondary,
  },
  loadingIndicator: { marginTop: 60 },
  bottomSpacer: { height: 32 },
});

export const moodCalendarStyles = StyleSheet.create({
  section: {
    marginHorizontal: 20,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 16,
    marginBottom: 0,
    overflow: 'hidden',
    shadowColor: '#1A3A4A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.07,
    shadowRadius: 12,
    elevation: 3,
  },
  header: {
    position: 'relative',
    alignItems: 'center',
    marginBottom: 14,
    minHeight: 30,
  },
  monthSelector: {
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 12,
    minHeight: 30,
  },
  title: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 19,
    color: Colors.textPrimary,
    textTransform: 'capitalize',
    textAlign: 'center',
  },
  monthChevronWrap: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: 'rgba(110, 133, 151, 0.16)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  countBadge: {
    position: 'absolute',
    right: 0,
    top: 6,
    fontFamily: 'Nunito_600SemiBold',
    fontSize: 13,
    color: TRACKER_ACTION_BLUE,
    lineHeight: 18,
    width: 58,
    textAlign: 'right',
  },
  pickerPanel: {
    backgroundColor: '#F7FAFC',
    borderRadius: 16,
    padding: 12,
    marginBottom: 16,
  },
  yearRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 18,
    marginBottom: 12,
  },
  yearButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  yearButtonText: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 22,
    color: Colors.teal,
    lineHeight: 24,
  },
  yearText: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 16,
    color: Colors.textPrimary,
  },
  monthGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  monthChip: {
    width: '23%',
    borderRadius: 14,
    paddingVertical: 8,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
  },
  monthChipActive: {
    backgroundColor: Colors.teal,
  },
  monthChipText: {
    fontFamily: 'Nunito_600SemiBold',
    fontSize: 12,
    color: Colors.textSecondary,
  },
  monthChipTextActive: {
    color: Colors.textLight,
  },
  pickerBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(26, 58, 74, 0.34)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 26,
  },
  pickerPopup: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    padding: 18,
    shadowColor: '#1A3A4A',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.18,
    shadowRadius: 22,
    elevation: 8,
  },
  pickerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  pickerTitle: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 18,
    color: Colors.textPrimary,
  },
  pickerCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#EEF4F8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pickerCloseText: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 16,
    color: Colors.textPrimary,
    lineHeight: 18,
  },
  pickerColumns: {
    flexDirection: 'row',
    gap: 12,
  },
  pickerColumn: {
    flex: 1,
  },
  pickerColumnLabel: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 13,
    color: Colors.textPrimary,
    marginBottom: 8,
  },
  pickerScroll: {
    maxHeight: 188,
    borderRadius: 16,
    backgroundColor: '#F7FAFC',
    padding: 6,
  },
  pickerOption: {
    minHeight: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
    paddingHorizontal: 12,
  },
  pickerOptionActive: {
    backgroundColor: TRACKER_ACTION_BLUE,
  },
  pickerOptionText: {
    fontFamily: 'Nunito_600SemiBold',
    fontSize: 14,
    color: Colors.textSecondary,
  },
  pickerOptionTextActive: {
    color: '#FFFFFF',
  },
  manualPanel: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 14,
  },
  manualInput: {
    flex: 1,
    minHeight: 44,
    borderRadius: 16,
    backgroundColor: '#F7FAFC',
    borderWidth: 1,
    borderColor: '#DDEAF1',
    paddingHorizontal: 14,
    fontFamily: 'Nunito_600SemiBold',
    fontSize: 15,
    color: Colors.textPrimary,
    textAlign: 'center',
  },
  pickerHint: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 12,
    color: Colors.textSecondary,
    textAlign: 'center',
    marginTop: 12,
  },
  pickerFooter: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 16,
  },
  pickerCancel: {
    flex: 1,
    minHeight: 46,
    borderRadius: 24,
    backgroundColor: '#EEF4F8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pickerCancelText: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 14,
    color: Colors.textSecondary,
  },
  pickerApply: {
    flex: 1,
    minHeight: 46,
    borderRadius: 24,
    backgroundColor: TRACKER_ACTION_BLUE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pickerApplyText: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 14,
    color: '#FFFFFF',
  },
  weekdayRow: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  weekdayCell: {
    flex: 1,
    alignItems: 'center',
  },
  weekdayText: {
    fontFamily: 'Nunito_600SemiBold',
    fontSize: 11,
    color: Colors.textSecondary,
    letterSpacing: 0.5,
  },
  weekRow: {
    flexDirection: 'row',
    marginBottom: 4,
  },
  dayCell: {
    flex: 1,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  dayCircle: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  dayCellOutOfMonth: {
    opacity: 0.2,
  },
  dayCellFuture: {
    opacity: 0.35,
  },
  dayCellLogged: {
    backgroundColor: '#C4DDED',
  },
  dayCellToday: {
    backgroundColor: '#2E6F8E',
    shadowColor: '#2E6F8E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 4,
  },
  dayCellSelected: {
    borderWidth: 1.5,
    borderColor: Colors.teal,
    backgroundColor: 'transparent',
  },
  dayNumber: {
    fontFamily: 'Nunito_600SemiBold',
    fontSize: 14,
    color: Colors.textSecondary,
  },
  dayNumberLogged: {
    color: Colors.textPrimary,
    fontFamily: 'Nunito_700Bold',
  },
  dayNumberToday: {
    color: Colors.textLight,
    fontFamily: 'Nunito_700Bold',
  },
  dayNumberSelected: {
    color: Colors.teal,
    fontFamily: 'Nunito_700Bold',
  },
  loggedDot: {
    position: 'absolute',
    bottom: 4,
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: Colors.teal,
  },
  loggedDotSelected: {
    backgroundColor: Colors.textLight,
  },
  activityPanel: {
    marginTop: 14,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  activityTitle: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 16,
    color: Colors.textPrimary,
    marginBottom: 10,
  },
  activityEmpty: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 15,
    color: Colors.textSecondary,
    paddingVertical: 8,
  },
  activityCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.foam,
    borderRadius: 12,
    padding: 12,
    gap: 12,
    marginBottom: 8,
  },
  activityEmoji: {
    fontSize: 26,
  },
  activityIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: Colors.teal + '22',
    alignItems: 'center',
    justifyContent: 'center',
  },
  activityIcon: {
    fontSize: 20,
  },
  activityBody: {
    flex: 1,
  },
  activityLabel: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 15,
    color: Colors.textPrimary,
    marginBottom: 2,
  },
  activitySub: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 13,
    color: Colors.textSecondary,
  },
  activityChevron: {
    fontFamily: 'Nunito_600SemiBold',
    fontSize: 20,
    color: Colors.textSecondary,
  },
});

export const moodLineChartStyles = StyleSheet.create({
  card: {
    marginHorizontal: 20,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    marginBottom: 0,
    shadowColor: '#1A3A4A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.07,
    shadowRadius: 12,
    elevation: 3,
  },
  header: {
    marginBottom: 16,
  },
  title: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 19,
    color: Colors.textPrimary,
    marginBottom: 2,
  },
  subtitle: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 12,
    color: Colors.textSecondary,
  },
  toggle: {
    flexDirection: 'row',
    backgroundColor: Colors.foam,
    borderRadius: 20,
    padding: 3,
    marginTop: 4,
    marginBottom: 12,
  },
  toggleBtn: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 18,
    alignItems: 'center',
  },
  toggleBtnActive: { backgroundColor: TRACKER_ACTION_BLUE },
  toggleText: {
    fontFamily: 'Nunito_600SemiBold',
    fontSize: 12,
    color: Colors.textSecondary,
  },
  toggleTextActive: { color: Colors.textLight },
  chartWrap: {
    flexDirection: 'row',
    marginTop: 8,
  },
  yAxis: {
    width: 18,
    justifyContent: 'space-between',
    paddingVertical: 4,
  },
  yLabel: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 9,
    color: Colors.textSecondary,
    textAlign: 'right',
  },
  plotWrap: {
    flex: 1,
    marginLeft: 6,
  },
  plot: {
    position: 'relative',
  },
  gridLine: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: '#EEF4F8',
    opacity: 0.65,
  },
  lineSegment: {
    position: 'absolute',
    backgroundColor: TRACKER_ACTION_BLUE,
  },
  dot: {
    position: 'absolute',
    backgroundColor: TRACKER_ACTION_BLUE,
  },
  dotCurrent: {
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: TRACKER_ACTION_BLUE,
  },
  xAxisRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  xLabel: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 9,
    color: Colors.textSecondary,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  summaryItem: {
    alignItems: 'center',
    flex: 1,
  },
  summaryNum: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 18,
    color: Colors.textPrimary,
  },
  summaryLabel: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 11,
    color: Colors.textSecondary,
    marginTop: 2,
    textAlign: 'center',
  },
  empty: {
    paddingVertical: 32,
    alignItems: 'center',
  },
  emptyText: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 13,
    color: Colors.textSecondary,
    textAlign: 'center',
  },
});

export const waterTrackerStyles = StyleSheet.create({
  card: {
    marginHorizontal: 20,
    marginTop: 20,
    backgroundColor: Colors.foam,
    borderRadius: 18,
    padding: 18,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  title: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 18,
    color: Colors.textPrimary,
  },
  subtitle: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 13,
    color: Colors.textSecondary,
    marginTop: 2,
  },
  mainRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 6,
  },
  counterBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: Colors.wave,
    alignItems: 'center',
    justifyContent: 'center',
  },
  counterBtnDisabled: {
    backgroundColor: '#B8D9E3',
  },
  counterBtnText: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 26,
    color: Colors.textLight,
    lineHeight: 30,
  },
  glassWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  glass: {
    width: 54,
    height: 72,
    borderLeftWidth: 3,
    borderRightWidth: 3,
    borderBottomWidth: 3,
    borderTopWidth: 1.5,
    borderColor: Colors.teal,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
    justifyContent: 'flex-end',
    overflow: 'hidden',
    backgroundColor: Colors.foam,
  },
  glassFill: {
    width: '100%',
    backgroundColor: Colors.wave,
    opacity: 0.9,
  },
  glassCount: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 24,
    color: Colors.textPrimary,
    marginTop: 10,
  },
  glassCountGoal: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 16,
    color: Colors.textSecondary,
  },
  glassLabel: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 12,
    color: Colors.textSecondary,
  },
  footerRow: {
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  footerText: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 13,
    color: Colors.textSecondary,
  },
  footerBold: {
    fontFamily: 'Nunito_700Bold',
    color: Colors.textPrimary,
  },
});

export const sleepTrackerStyles = StyleSheet.create({
  card: {
    marginHorizontal: 20,
    marginTop: 20,
    backgroundColor: Colors.foam,
    borderRadius: 18,
    padding: 18,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  title: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 18,
    color: Colors.textPrimary,
  },
  subtitle: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 13,
    color: Colors.textSecondary,
    marginTop: 2,
  },
  mainRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 6,
  },
  numberWrap: { flex: 1 },
  bigNumber: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 31,
    color: Colors.textPrimary,
  },
  unit: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 13,
    color: Colors.textSecondary,
    marginTop: 4,
  },
  ringWrap: {
    width: 72,
    height: 72,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ringBg: {
    position: 'absolute',
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 8,
    borderColor: Colors.mist,
  },
  ringFill: {
    position: 'absolute',
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 8,
    borderColor: Colors.ocean,
    borderRightColor: 'transparent',
    borderBottomColor: 'transparent',
  },
  ringPct: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 13,
    color: Colors.textPrimary,
  },
  emptyText: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 13,
    color: Colors.textSecondary,
    lineHeight: 18,
    paddingVertical: 8,
  },
  retryBtn: {
    marginTop: 10,
    alignSelf: 'flex-start',
    backgroundColor: Colors.teal,
    borderRadius: 20,
    paddingHorizontal: 18,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  retryText: {
    fontFamily: 'Nunito_700Bold',
    color: Colors.textLight,
    fontSize: 13,
    lineHeight: 16,
    textAlign: 'center',
    includeFontPadding: false,
    flexShrink: 1,
  },
  footerRow: {
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  footerText: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 13,
    color: Colors.textSecondary,
  },
  footerBold: {
    fontFamily: 'Nunito_700Bold',
    color: Colors.textPrimary,
  },
});

export const stepsTrackerStyles = StyleSheet.create({
  card: {
    marginHorizontal: 20,
    marginTop: 20,
    backgroundColor: Colors.foam,
    borderRadius: 18,
    padding: 18,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  title: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 18,
    color: Colors.textPrimary,
  },
  subtitle: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 13,
    color: Colors.textSecondary,
    marginTop: 2,
  },
  mainRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 6,
  },
  numberWrap: {
    flex: 1,
  },
  bigNumber: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 34,
    color: Colors.textPrimary,
  },
  unit: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 13,
    color: Colors.textSecondary,
    marginTop: 2,
  },
  ringWrap: {
    width: 72,
    height: 72,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ringBg: {
    position: 'absolute',
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 8,
    borderColor: Colors.mist,
  },
  ringFill: {
    position: 'absolute',
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 8,
    borderColor: Colors.wave,
    borderRightColor: 'transparent',
    borderBottomColor: 'transparent',
  },
  ringPct: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 13,
    color: Colors.textPrimary,
  },
  emptyText: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 13,
    color: Colors.textSecondary,
    lineHeight: 18,
    paddingVertical: 8,
  },
  retryBtn: {
    marginTop: 10,
    alignSelf: 'flex-start',
    backgroundColor: Colors.teal,
    borderRadius: 20,
    paddingHorizontal: 18,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  retryText: {
    fontFamily: 'Nunito_700Bold',
    color: Colors.textLight,
    fontSize: 13,
    lineHeight: 16,
    textAlign: 'center',
    includeFontPadding: false,
    flexShrink: 1,
  },
  footerRow: {
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  footerText: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 13,
    color: Colors.textSecondary,
  },
  footerBold: {
    fontFamily: 'Nunito_700Bold',
    color: Colors.textPrimary,
  },
});
