import { StyleSheet } from 'react-native';
import { Colors } from '../../constants/colors';

export const chatStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.foam },
  flex: { flex: 1 },

  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(46, 111, 142, 0.12)',
    backgroundColor: Colors.foam,
  },
  headerBackButton: {
    alignSelf: 'center',
  },
  headerAvatarWrap: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#C4DDED',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    shadowColor: '#5B9BC8',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.22,
    shadowRadius: 10,
    elevation: 4,
  },
  soraDrop: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderTopLeftRadius: 6,
    backgroundColor: '#5B9BC8',
    transform: [{ rotate: '45deg' }],
  },
  soraFace: {
    position: 'absolute',
    left: 13,
    right: 13,
    top: 27,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  soraEye: {
    width: 3,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: '#1A3A4A',
  },
  soraMouth: {
    width: 7,
    height: 2,
    borderRadius: 1,
    backgroundColor: '#1A3A4A',
  },
  headerName: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 16,
    color: '#1A3A4A',
  },
  headerStatus: {
    fontFamily: 'Nunito_600SemiBold',
    fontSize: 11,
    color: '#3D7A4A',
    marginTop: 1,
  },
  headerTextBlock: {
    flex: 1,
  },

  messages: { flex: 1 },
  messagesContent: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    gap: 4,
  },
  timeLabel: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 11,
    color: Colors.textSecondary,
    textAlign: 'center',
    marginVertical: 8,
  },
  msgRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    marginBottom: 8,
    gap: 8,
  },
  msgRowAI: { justifyContent: 'flex-start' },
  msgRowUser: { justifyContent: 'flex-end' },
  aiAvatar: {
    width: 28, height: 28,
    borderRadius: 14,
    backgroundColor: '#C4DDED',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  aiAvatarDrop: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderTopLeftRadius: 4,
    backgroundColor: '#5B9BC8',
    transform: [{ rotate: '45deg' }],
  },
  aiAvatarFace: {
    position: 'absolute',
    left: 7,
    right: 7,
    top: 17,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 1.5,
  },
  aiAvatarEye: {
    width: 2,
    height: 2,
    borderRadius: 1,
    backgroundColor: '#1A3A4A',
  },
  aiAvatarMouth: {
    width: 4,
    height: 1.5,
    borderRadius: 1,
    backgroundColor: '#1A3A4A',
  },
  bubble: {
    maxWidth: '75%',
    borderRadius: 18,
    padding: 12,
  },
  bubbleAI: {
    backgroundColor: '#EAF4F8',
    borderBottomLeftRadius: 4,
  },
  bubbleUser: {
    backgroundColor: '#2E6F8E',
    borderBottomRightRadius: 4,
    shadowColor: '#1A3A4A',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.14,
    shadowRadius: 8,
    elevation: 3,
  },
  bubbleTyping: {
    paddingVertical: 14,
    paddingHorizontal: 16,
  },
  bubbleText: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 14,
    lineHeight: 20,
  },
  bubbleTextAI: { color: '#111827' },
  bubbleTextUser: { color: '#FFFFFF', fontFamily: 'Nunito_600SemiBold' },
  typingDots: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 16,
    color: Colors.textSecondary,
    letterSpacing: 4,
  },

  quickReplies: {
    maxHeight: 48,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  quickRepliesContent: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    gap: 8,
  },
  quickReply: {
    backgroundColor: Colors.surface,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  quickReplyText: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 13,
    color: Colors.textPrimary,
  },

  inputWrap: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 14,
    gap: 10,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
    backgroundColor: Colors.foam,
  },
  input: {
    flex: 1,
    backgroundColor: Colors.surface,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 10,
    fontFamily: 'Nunito_400Regular',
    fontSize: 14,
    color: Colors.textPrimary,
    maxHeight: 100,
  },
  sendBtn: {
    width: 40, height: 40,
    borderRadius: 20,
    backgroundColor: Colors.teal,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendBtnDisabled: {
    backgroundColor: Colors.border,
  },
  sendBtnText: {
    fontSize: 18,
    color: Colors.textLight,
    fontFamily: 'Nunito_700Bold',
  },
});
