import { StyleSheet } from 'react-native';
import { Colors } from '../../constants/colors';

const PROFILE_BG = '#F4F8FB';
const GLASS_BG = 'rgba(255,255,255,0.78)';
const GLASS_BORDER = 'rgba(124,179,212,0.42)';
const BLUE = '#2E6F8E';
const BLUE_SOFT = '#DCECF5';
const TEXT = '#1A3A5C';
const MUTED = '#4A7A9B';

export const profileStyles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: PROFILE_BG,
  },
  scrollContent: {
    paddingBottom: 128,
  },
  header: {
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 12,
    alignItems: 'center',
  },
  headerTitle: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 22,
    color: TEXT,
  },
  avatarCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: GLASS_BG,
    marginHorizontal: 24,
    borderRadius: 22,
    padding: 16,
    marginBottom: 12,
    gap: 14,
    borderWidth: 1.2,
    borderColor: GLASS_BORDER,
    shadowColor: '#1A3A4A',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 5,
  },
  avatarCircle: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: BLUE_SOFT,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: GLASS_BORDER,
    overflow: 'hidden',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
  },
  avatarWrap: {
    position: 'relative',
    width: 64,
    height: 64,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarCameraBadge: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: BLUE,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  avatarViewerOverlay: {
    flex: 1,
    backgroundColor: '#081824',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarViewerClose: {
    position: 'absolute',
    top: 42,
    right: 18,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.14)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
  },
  avatarViewerCloseText: {
    color: '#FFFFFF',
    fontSize: 28,
    lineHeight: 32,
  },
  avatarViewerImage: {
    width: '100%',
    height: '100%',
  },
  avatarOptionBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(8,24,36,0.38)',
    justifyContent: 'flex-end',
    padding: 18,
  },
  avatarOptionSheet: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 16,
    gap: 2,
  },
  avatarOptionTitle: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 15,
    color: TEXT,
    textAlign: 'center',
    marginBottom: 8,
  },
  avatarOptionBtn: {
    paddingVertical: 14,
    alignItems: 'center',
  },
  avatarOptionBtnBorder: {
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(124,179,212,0.24)',
  },
  avatarOptionText: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 14,
    color: BLUE,
  },
  avatarOptionCancel: {
    marginTop: 8,
    borderRadius: 16,
    backgroundColor: '#F4F8FB',
  },
  avatarOptionCancelText: {
    color: MUTED,
  },
  avatarText: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 19,
    color: BLUE,
  },
  avatarInfo: {
    flex: 1,
    minWidth: 0,
  },
  avatarName: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 16,
    color: TEXT,
    marginBottom: 2,
  },
  avatarSub: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 13,
    color: MUTED,
  },
  avatarAge: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 11,
    color: MUTED,
    marginTop: 2,
  },
  avatarChevron: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 24,
    color: BLUE,
    lineHeight: 26,
    paddingLeft: 4,
  },
  editBtn: {
    display: 'none',
  },
  editBtnText: {
    color: BLUE,
  },
  streakCard: {
    flexDirection: 'row',
    backgroundColor: GLASS_BG,
    marginHorizontal: 24,
    borderRadius: 22,
    paddingVertical: 16,
    paddingHorizontal: 14,
    marginBottom: 12,
    alignItems: 'center',
    borderWidth: 1.2,
    borderColor: GLASS_BORDER,
    shadowColor: '#1A3A4A',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.10,
    shadowRadius: 14,
    elevation: 4,
  },
  streakLeft: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
  },
  streakFire: {
    display: 'none',
  },
  streakRight: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
  },
  statTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    alignSelf: 'center',
    minWidth: 62,
  },
  statIconBox: {
    width: 20,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  streakNum: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 18,
    color: TEXT,
    textAlign: 'left',
    lineHeight: 22,
    minWidth: 24,
  },
  streakLabel: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 10,
    color: MUTED,
    textAlign: 'center',
    marginTop: 1,
  },
  streakDivider: {
    width: 1,
    height: 54,
    backgroundColor: 'rgba(124,179,212,0.28)',
    marginHorizontal: 8,
  },
  reminderCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: GLASS_BG,
    marginHorizontal: 24,
    borderRadius: 22,
    padding: 16,
    marginBottom: 20,
    borderWidth: 1.2,
    borderColor: GLASS_BORDER,
    shadowColor: '#1A3A4A',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.10,
    shadowRadius: 14,
    elevation: 4,
  },
  reminderLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  reminderIcon: {
    display: 'none',
  },
  reminderLabel: {
    fontFamily: 'Nunito_600SemiBold',
    fontSize: 14,
    color: TEXT,
    marginBottom: 2,
  },
  reminderSub: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 11,
    color: MUTED,
    lineHeight: 16,
    maxWidth: 230,
  },
  section: {
    paddingHorizontal: 24,
    marginBottom: 16,
  },
  sectionTitle: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 12,
    color: MUTED,
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    paddingLeft: 2,
  },
  sectionCard: {
    backgroundColor: GLASS_BG,
    borderRadius: 22,
    overflow: 'hidden',
    borderWidth: 1.2,
    borderColor: GLASS_BORDER,
    shadowColor: '#1A3A4A',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.10,
    shadowRadius: 14,
    elevation: 4,
  },
  settingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 15,
    paddingHorizontal: 16,
    gap: 12,
  },
  settingRowBorder: {
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(124,179,212,0.24)',
  },
  settingIcon: {
    display: 'none',
  },
  settingIconBox: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  settingLabel: {
    flex: 1,
    fontFamily: 'Nunito_600SemiBold',
    fontSize: 14,
    color: TEXT,
  },
  settingArrow: {
    fontSize: 22,
    color: BLUE,
    lineHeight: 24,
  },
  logoutBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    padding: 16,
    gap: 10,
    borderWidth: 1.2,
    borderColor: 'rgba(211,47,47,0.22)',
    shadowColor: '#1A3A4A',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },
  logoutIcon: {
    display: 'none',
  },
  logoutText: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 15,
    color: Colors.alertHigh,
  },
  version: {
    fontFamily: 'Nunito_400Regular',
    fontSize: 12,
    color: MUTED,
    textAlign: 'center',
    paddingVertical: 8,
  },
  bottomSpacer: {
    height: 128,
  },
});
